"""
universe.py
──────────────────────────────────────────────────────────────────────────────
Single source of truth for the MSCI ticker universe.

Responsibilities:
  - CSV path constants for all 9 country classification files
  - Ghost-ticker detection (Bloomberg placeholders, malformed symbols)
  - Known-dead ticker registry (sanctioned equities, unsupported exchanges)
  - Ticker runtime overrides (symbol renames, corporate actions)
  - load_universe() → deduplicated DataFrame consumed by gc_engine and scan

NOT responsible for:
  - Generating the CSVs (→ update_msci_world_classification.py)
  - OHLCV data (→ gc_engine.py, future data_engine.py)
  - Fundamental/earnings data (→ gc_engine.py, future data_engine.py)
  - Chart pattern detection (→ scan.py)

Consumers:
  from universe import load_universe, is_ghost_ticker, KNOWN_DEAD_TICKERS

VERSION HISTORY
───────────────
1.0.0  Extracted from gc_engine.py (load_universe, is_ghost_ticker,
       TICKER_OVERRIDES, KNOWN_DEAD_TICKERS, all CSV path constants).
       Replaces duplicated _is_ghost_ticker() in scan.py.
       Both gc_engine.py and scan.py now import from here.
       Companion: gc_engine.py 0.5.5, scan.py v98.
"""

from __future__ import annotations

UNIVERSE_VERSION = "1.0.0"

import os
import re
from pathlib import Path
from typing import Dict, List

import pandas as pd

# ── Directory layout ──────────────────────────────────────────────────────────
BASE_DIR   = Path(os.environ.get("BASE_DIR", Path(__file__).resolve().parent))
CONFIG_DIR = BASE_DIR / "config"
DOCS_DIR   = BASE_DIR / "docs"
GC_STATE_PATH = DOCS_DIR / "gc_state.json"

# ── MSCI universe CSVs ────────────────────────────────────────────────────────
# All generated by tools/update_msci_world_classification.py.
# Missing files are skipped gracefully in load_universe() (first-run safe).
MSCI_CSV     = CONFIG_DIR / "msci_world_classification.csv"     # MSCI World (IWDA)
MSCI_EM_CSV  = CONFIG_DIR / "msci_em_classification.csv"        # MSCI EM (EIMI)
MSCI_KR_CSV  = CONFIG_DIR / "msci_korea_classification.csv"     # Korea  (EWY → .KS)
MSCI_JP_CSV  = CONFIG_DIR / "msci_japan_classification.csv"     # Japan  (EWJ → .T)
MSCI_TW_CSV  = CONFIG_DIR / "msci_taiwan_classification.csv"    # Taiwan (EWT → .TW)
MSCI_CN_CSV  = CONFIG_DIR / "msci_china_classification.csv"     # China  (MCHI → .SS/.SZ)
MSCI_HK_CSV  = CONFIG_DIR / "msci_hk_classification.csv"        # HK     (EWH → .HK)
MSCI_SA_CSV  = CONFIG_DIR / "msci_saudi_classification.csv"     # Saudi  (manual → .SR)
MSCI_NZL_CSV = CONFIG_DIR / "msci_nzl_classification.csv"       # NZL    (manual → .NZ)

# ── Dedup priority ────────────────────────────────────────────────────────────
# Lower number = higher priority. When the same ticker appears in multiple CSVs
# the lowest-number source wins.
# World=1 (most authoritative for DM), country ETFs=2, EM=3 (broadest, least specific).
_SOURCE_PRIORITY: Dict[str, int] = {
    "world":  1,
    "japan":  2,
    "taiwan": 2,
    "china":  2,
    "hk":     2,
    "saudi":  2,
    "nzl":    2,
    "korea":  2,
    "em":     3,
}

# ── Ticker runtime overrides ──────────────────────────────────────────────────
# Applied at load time — corrects symbol renames and corporate actions that
# can't be known when the CSV is built.
# If a correction can be derived from the iShares export (company name,
# exchange, country), it belongs in update_msci_world_classification.py instead.
TICKER_OVERRIDES: Dict[str, str] = {
    # (currently empty — all known overrides live in update_msci_world_classification.py)
}

# ── Known-dead tickers ────────────────────────────────────────────────────────
# Permanently skip before any API call — these return 404 on every yfinance
# request and waste ~4-6 seconds each per run.
# Categories:
#   - Sanctioned Russian equities: will never be re-listed on Yahoo Finance
#   - Gulf tickers confirmed to have no Yahoo quoteSummary support
# To add: append ticker + comment. Do NOT put correctable symbols here —
# use TICKER_OVERRIDES for those.
KNOWN_DEAD_TICKERS: set = {
    # Sanctioned Russian equities — permanently 404 on Yahoo Finance
    "AFKS", "AFLT", "BLDN", "BRES", "CBOM", "CBQK", "CHMF",
    "FEES", "FLOT", "GAZP", "GEMC", "GISS", "GMKN", "IRAO",
    "LKOH", "LSRG", "MGNT", "NLMK", "NVTK", "PHOR", "PIKK",
    "RTKM", "RUAL", "SBER", "SGZH", "SNGS", "SNGSP", "TATN",
    "TCSG", "UPRO", "VKCO",
    # Gulf tickers with no Yahoo Finance quoteSummary support
    "DHBK", "DUBK", "IGRD", "IQCD", "UDCD", "VFQS",
}

# ── Ghost ticker detection ────────────────────────────────────────────────────
_GHOST_PATTERN = re.compile(
    r"^-$"                    # bare dash
    r"|^\d+D?$"               # pure numeric, optionally ending in D
    r"|^[A-Z]{1,5}\d{6,}D$"  # alpha prefix + long numeric + D
    r"|^\.$"                  # bare dot
    r"|^DUMMY$"               # iShares CSV placeholder row
)


def is_ghost_ticker(ticker: str) -> bool:
    """Return True for any symbol that will never resolve on Yahoo Finance.

    Catches: bare numerics (raw Japanese/Korean/etc codes without exchange suffix),
    Bloomberg D-codes, bare-dash null rows, and multi-dot malformed symbols.

    This is a lightweight safety net applied at load time. The primary filtering
    happens during CSV generation in update_msci_world_classification.py.
    """
    t = str(ticker).strip()
    if not t:
        return True
    if "." not in t and t.replace("-", "").isdigit():
        return True   # pure numeric without suffix → never valid on Yahoo
    if t.count(".") > 1:
        return True   # multi-dot = malformed (e.g. BAJAJ.AUTO.NS)
    return bool(_GHOST_PATTERN.match(t))


# ── Universe loader ───────────────────────────────────────────────────────────

def load_universe() -> pd.DataFrame:
    """Load all MSCI country CSVs and return a deduplicated ticker universe.

    Sources loaded (in priority order — lower number wins for duplicates):
      1. MSCI World (IWDA)           — Developed Markets primary
      2. Country ETFs: Japan, Taiwan, China, HK, Saudi Arabia, New Zealand, Korea
         — dedicated ETFs with better exchange-suffix handling than EM catchall
      3. MSCI EM (EIMI)              — broadest coverage, lowest specificity

    Each CSV is skipped gracefully if the file doesn't exist (first-run safe).
    Returns DataFrame with columns: Ticker, Company, Country, Sector.
    """
    _sources = [
        ("world",  MSCI_CSV),
        ("japan",  MSCI_JP_CSV),
        ("taiwan", MSCI_TW_CSV),
        ("china",  MSCI_CN_CSV),
        ("hk",     MSCI_HK_CSV),
        ("saudi",  MSCI_SA_CSV),
        ("nzl",    MSCI_NZL_CSV),
        ("korea",  MSCI_KR_CSV),
        ("em",     MSCI_EM_CSV),
    ]

    frames = []
    for source_key, csv_path in _sources:
        if not csv_path.exists():
            print(f"[universe] {source_key.upper()} CSV not found at {csv_path} — skipped "
                  f"(run update_msci_world_classification.py --universe {source_key} to generate)")
            continue
        try:
            df = pd.read_csv(csv_path, dtype=str)
            df["Ticker"] = df["Ticker"].astype(str).str.strip()
            df = df[df["Ticker"].str.len() > 0]
            df["_source"] = source_key
            df["_priority"] = _SOURCE_PRIORITY.get(source_key, 99)
            frames.append(df)
            print(f"[universe] Loaded {len(df):>5} tickers from {source_key.upper()} CSV")
        except Exception as e:
            print(f"[universe] Error loading {source_key.upper()} CSV: {e}")

    if not frames:
        return pd.DataFrame(columns=["Ticker", "Company", "Country", "Sector"])

    combined = pd.concat(frames, ignore_index=True)

    # Dedup: sort ascending so lowest priority number (= highest priority) wins
    combined = combined.sort_values("_priority", ascending=True)
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")
    combined = combined.drop(columns=["_source", "_priority"], errors="ignore")

    # Normalize Borsa Istanbul tickers: strip -E suffix (KCHOL-E.IS → KCHOL.IS)
    before_norm = combined["Ticker"].copy()
    combined["Ticker"] = combined["Ticker"].str.replace(r"-E\.IS$", ".IS", regex=True)
    normalized = (combined["Ticker"] != before_norm).sum()
    if normalized:
        print(f"[universe] Normalized {normalized} Turkish .IS tickers (stripped -E suffix)")
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")

    # Apply runtime ticker overrides (symbol renames, corporate actions)
    combined["Ticker"] = combined["Ticker"].replace(TICKER_OVERRIDES)
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")

    # Ghost filter — safety net for anything that slipped through CSV build
    before = len(combined)
    combined = combined[~combined["Ticker"].apply(is_ghost_ticker)]
    dropped = before - len(combined)
    if dropped:
        print(f"[universe] Dropped {dropped} ghost/placeholder tickers")

    print(f"[universe] Total: {len(combined)} unique tickers")
    return combined.reset_index(drop=True)
