"""
universe.py
──────────────────────────────────────────────────────────────────────────────
Single source of truth for the MSCI ticker universe.

Responsibilities:
  - CSV path constants for MSCI World and MSCI EM classification files
  - Ghost-ticker detection (Bloomberg placeholders, malformed symbols)
  - Known-dead ticker registry (sanctioned equities, unsupported exchanges)
  - Ticker runtime overrides (symbol renames, corporate actions)
  - load_universe() → deduplicated DataFrame consumed by gc_engine and scan
  - Generating the CSVs (→ update_msci_world_classification.py)
  - OHLCV data (→ gc_engine.py, future data_engine.py)
  - Fundamental/earnings data (→ gc_engine.py, future data_engine.py)
  - Chart pattern detection (→ scan.py)

Consumers:
  from universe import (
      load_universe, is_ghost_ticker, KNOWN_DEAD_TICKERS, TICKER_OVERRIDES,
      DEAD_MARKET_SUFFIXES, EU_SUFFIXES, MIN_MCAP_US_EU, MIN_MCAP_OTHER,
      mcap_threshold, FMP_ALPHA_BATCH_SUFFIXES, ADR_MAP, get_fmp_symbol,
  )

VERSION HISTORY
───────────────
1.0.0  Extracted from gc_engine.py (load_universe, is_ghost_ticker,
       TICKER_OVERRIDES, KNOWN_DEAD_TICKERS, all CSV path constants).
       Replaces duplicated _is_ghost_ticker() in scan.py.
       Both gc_engine.py and scan.py now import from here.
       Companion: gc_engine.py 0.5.5, scan.py v98.
1.1.0  Exchange + market classification added (previously defined in gc_engine.py).
       DEAD_MARKET_SUFFIXES (KL, PS, AD), EU_SUFFIXES (17 exchanges), MIN_MCAP_US_EU ($2B),
       MIN_MCAP_OTHER ($5B), mcap_threshold() moved here from gc_engine.py 0.6.0–0.6.2.
       FMP_ALPHA_BATCH_SUFFIXES added (all alpha-suffix exchanges globally: EU + Canada +
       Australia + India + Brazil + Mexico + Turkey + Indonesia + S.Africa + Chile + Qatar +
       Kuwait + Singapore). ADR_MAP (25 entries) + get_fmp_symbol() added: maps numeric APAC
       Yahoo tickers to US ADR symbols for FMP analyst consensus (2330.TW→TSM, 7203.T→TM etc.).
       Companion: gc_engine.py 0.6.2–0.6.3, scan.py v98.
1.2.0  load_universe() now filters DEAD_MARKET_SUFFIXES and KNOWN_DEAD_TICKERS
       at source — tickers on dead exchanges (KL/PS/AD/DU) and known-dead symbols
       never enter gc_engine or scan.py at all. Added DU (UAE Dubai, 95% dead)
       to DEAD_MARKET_SUFFIXES. Effect: ~145 fewer tickers enter pipeline,
       preventing dead tickers from inflating the active count in gc_state.
       Companion: gc_engine.py 0.6.6, scan.py v99.
1.4.0  Simplified to 2 sources: MSCI World (IWDA) + MSCI EM standard.
       Removed all 7 country-ETF CSV constants and _SOURCE_PRIORITY entries:
       japan, taiwan, china, hk, saudi, nzl, korea.
       Companion: update_msci_world_classification.py v3.0.0 (reads iShares
       XLS directly via exact exchange-name → Yahoo suffix table, ~2,100
       total tickers replacing the old ~6,400 EIMI-based universe).
1.5.0  _normalize_ticker() — comprehensive Yahoo Finance ticker normalization:
       (1) Turkey: ASELS.E.IS / ASELS-E.IS → ASELS.IS
       (2) Thailand NVDR: ADVANC.R.BK → ADVANC.BK
       (3) UAE remap: .AD/.DU → .AE (Yahoo unified UAE suffix)
       (4) London double-dot: BA..L → BA.L
       (5) Class-share 2-dot rule: RCI.B.TO → RCI-B.TO, GIB.A.TO → GIB-A.TO,
           BAJAJ.AUTO.NS → BAJAJ-AUTO.NS (first dot → dash for multi-part names)
       TICKER_OVERRIDES: 2299955D.TO→CSU.TO, BRK.B→BRK-B, HEI.A→HEI-A
       DEAD_MARKET_SUFFIXES: removed AD/DU (now remapped to .AE, not dead)
       FMP_ALPHA_BATCH_SUFFIXES: added AE, KQ, BO
       MIN_MCAP_OTHER: lowered $5B→$2B (unified floor; FX conversion in gc_engine)
       .KQ (KOSDAQ) and .TWO (Taiwan Gretai) recognised in FMP suffix set
1.6.0  mcap floor lowered $2B → $1B USD (MIN_MCAP_US_EU = MIN_MCAP_OTHER = 1_000_000_000).
       TICKER_OVERRIDES: added BRKB→BRK-B, HEIA→HEI-A (iShares XLS omits the dot so the
       BRK.B/HEI.A overrides never fired from raw CSV; bare-symbol variants now handled).
       _normalize_ticker(): added Mexico asterisk strip — AC*.MX → AC.MX (asterisk in
       iShares XLS for voting-class shares breaks yfinance; stripped before any lookup).
       Companion: gc_engine.py 0.8.0, scan.py v102, export_universe.py v4.
"""

from __future__ import annotations

UNIVERSE_VERSION = "1.6.0"

import os
import re
from pathlib import Path
from typing import Dict, List

import pandas as pd

# ── Directory layout ──────────────────────────────────────────────────────────
BASE_DIR   = Path(os.environ.get("BASE_DIR", Path(__file__).resolve().parent))
CONFIG_DIR = BASE_DIR / "config"
DOCS_DIR   = BASE_DIR / "docs"
GC_STATE_PATH = DOCS_DIR / "gc_state.json"

# ── MSCI universe CSVs ────────────────────────────────────────────────────────
# Both generated by tools/update_msci_world_classification.py v3+.
# Missing files are skipped gracefully in load_universe() (first-run safe).
MSCI_CSV     = CONFIG_DIR / "msci_world_classification.csv"     # MSCI World  (~1,300 stocks)
MSCI_EM_CSV  = CONFIG_DIR / "msci_em_classification.csv"        # MSCI EM std (~830 stocks)

# ── Dedup priority ────────────────────────────────────────────────────────────
# Lower number = higher priority. World=1 (DM primary), EM=2.
# Country ETFs removed in v1.4.0 — exchange suffix now resolved directly from
# the iShares XLS Exchange column in update_msci_world_classification.py.
_SOURCE_PRIORITY: Dict[str, int] = {
    "world": 1,
    "em":    2,
}

# ── Ticker runtime overrides ──────────────────────────────────────────────────
# Applied at load time — corrects symbol renames and corporate actions that
# can't be known when the CSV is built.
# If a correction can be derived from the iShares export (company name,
# exchange, country), it belongs in update_msci_world_classification.py instead.
TICKER_OVERRIDES: Dict[str, str] = {
    # MSCI CSV errors — wrong Bloomberg placeholder, correct Yahoo ticker
    "2299955D.TO": "CSU.TO",     # Constellation Software Inc. → TSX: CSU
    # US dual-class shares: MSCI CSVs use dot notation, Yahoo Finance uses dash
    "BRK.B":  "BRK-B",          # Berkshire Hathaway Class B (dot form)
    "BRKB":   "BRK-B",          # Berkshire Hathaway Class B (bare form — iShares XLS)
    "HEI.A":  "HEI-A",          # Heico Corporation Class A (dot form)
    "HEIA":   "HEI-A",          # Heico Corporation Class A (bare form — iShares XLS)
    "HEI.B":  "HEI",            # Heico Corporation Class B (listed as HEI)
}

# ── Known-dead tickers ────────────────────────────────────────────────────────
# Permanently skip before any API call — these return 404 on every yfinance
# request and waste ~4-6 seconds each per run.
# Categories:
#   - Sanctioned Russian equities: will never be re-listed on Yahoo Finance
#   - Gulf tickers confirmed to have no Yahoo quoteSummary support
# To add: append ticker + comment. Do NOT put correctable symbols here —
# use TICKER_OVERRIDES for those.
KNOWN_DEAD_TICKERS: set = {
    # Sanctioned Russian equities — permanently 404 on Yahoo Finance
    "AFKS", "AFLT", "BLDN", "BRES", "CBOM", "CBQK", "CHMF",
    "FEES", "FLOT", "GAZP", "GEMC", "GISS", "GMKN", "IRAO",
    "LKOH", "LSRG", "MGNT", "NLMK", "NVTK", "PHOR", "PIKK",
    "RTKM", "RUAL", "SBER", "SGZH", "SNGS", "SNGSP", "TATN",
    "TCSG", "UPRO", "VKCO",
    # Gulf tickers with no Yahoo Finance quoteSummary support
    "DHBK", "DUBK", "IGRD", "IQCD", "UDCD", "VFQS",
}

# ── Ghost ticker detection ────────────────────────────────────────────────────
_GHOST_PATTERN = re.compile(
    r"^-$"                    # bare dash
    r"|^\d+D?$"               # pure numeric, optionally ending in D
    r"|^[A-Z]{1,5}\d{6,}D$"  # alpha prefix + long numeric + D
    r"|^\.$"                  # bare dot
    r"|^DUMMY$"               # iShares CSV placeholder row
)


def is_ghost_ticker(ticker: str) -> bool:
    """Return True for any symbol that will never resolve on Yahoo Finance.

    Catches: bare numerics (raw Japanese/Korean/etc codes without exchange suffix),
    Bloomberg D-codes, bare-dash null rows, and multi-dot malformed symbols.

    This is a lightweight safety net applied at load time. The primary filtering
    happens during CSV generation in update_msci_world_classification.py.
    """
    t = str(ticker).strip()
    if not t:
        return True
    if "." not in t and t.replace("-", "").isdigit():
        return True   # pure numeric without suffix → never valid on Yahoo
    if t.count(".") > 1:
        return True   # multi-dot = malformed (e.g. BAJAJ.AUTO.NS)
    return bool(_GHOST_PATTERN.match(t))


# ── Exchange & market classification ─────────────────────────────────────────
# All facts about "which exchange belongs to which tier" live here.
# gc_engine.py and scan.py import from this module — they never define their own.

# Dead-market suffixes: yfinance returns 0 usable data for these exchanges.
# Skipped entirely (same treatment as KNOWN_DEAD_TICKERS) to save API calls.
# Confirmed via gc_state.json: 0% EPS/Revenue coverage across all tickers.
DEAD_MARKET_SUFFIXES: set = {
    "KL",   # Malaysia — Bursa Malaysia, yfinance quoteSummary 404s universally
    "PS",   # Philippines — Philippine SE, same
    # NOTE: AD (Abu Dhabi) and DU (Dubai) removed from dead list.
    # _normalize_ticker() remaps .AD/.DU → .AE (Yahoo Finance's current suffix for UAE).
    # e.g. AIRARABIA.AD → AIRARABIA.AE per https://finance.yahoo.com/quote/AIRARABIA.AE/
}

# EU + CH + UK exchange suffixes for market-cap floor purposes.
# These are developed-market, reasonably liquid exchanges where $2B is the right floor.
EU_SUFFIXES: frozenset = frozenset({
    "L",   # London Stock Exchange
    "DE",  # XETRA Frankfurt
    "PA",  # Euronext Paris
    "AS",  # Euronext Amsterdam
    "MI",  # Borsa Italiana
    "MC",  # Madrid (BME)
    "ST",  # Stockholm (Nasdaq Nordic)
    "OL",  # Oslo Børs
    "HE",  # Helsinki (Nasdaq Nordic)
    "CO",  # Copenhagen (Nasdaq Nordic)
    "LS",  # Lisbon (Euronext)
    "BR",  # Brussels (Euronext)
    "AT",  # Athens (ATHEX)
    "IR",  # Dublin (Euronext)
    "SW",  # SIX Swiss Exchange
    "WA",  # Warsaw (GPW)
    "VI",  # Vienna (Wiener Börse)
})

# Market-cap floors — NOW UNIFIED at $2B USD across all markets.
# mcap values from yfinance are in LOCAL currency; gc_engine.py converts to USD
# using live FX rates before comparing to this floor.
# US (no suffix) + EU: $2B — same as before.
# All other markets (EM, APAC, MENA, LatAm): lowered from $5B → $2B USD.
# Rationale: MSCI EM constituents are by definition investable mid/large caps;
# applying a $5B USD floor was excluding legitimate EM mid-caps that simply have
# local currencies weaker than USD (e.g. 3B KWD ≈ $10B USD was passing before,
# but a 150B KRW ≈ $110M USD should correctly fail).
MIN_MCAP_US_EU: int = 1_000_000_000   # $1B USD
MIN_MCAP_OTHER: int = 1_000_000_000   # $1B USD (unified — FX conversion handles currency)


def mcap_threshold(ticker: str) -> int:
    """Return the minimum market-cap (USD) for the given ticker's exchange.

    US tickers (no suffix) and all EU_SUFFIXES exchanges → $2B.
    Everything else → $5B.
    """
    suffix = ticker.rsplit(".", 1)[-1] if "." in ticker else "US"
    if suffix == "US" or suffix in EU_SUFFIXES:
        return MIN_MCAP_US_EU
    return MIN_MCAP_OTHER


# FMP alpha-batch suffixes: exchanges where tickers have ALPHA bare symbols
# (e.g. RELIANCE.NS → RELIANCE, SAP.DE → SAP, VALE3.SA → VALE3).
# FMP can match these via /stable/earnings + /income-statement using the bare symbol.
# Excludes numeric-only exchanges (.T, .TW, .KS, .SS, .SZ, .HK, .SR) where bare
# symbols are numbers (2330, 6857, 000660) that FMP will not find.
FMP_ALPHA_BATCH_SUFFIXES: frozenset = frozenset({
    # EU / CH / UK
    "L",   "DE",  "PA",  "AS",  "SW",  "MI",  "MC",
    "ST",  "OL",  "HE",  "CO",  "WA",  "AT",  "VI",
    # North America (non-US)
    "TO",  # Toronto TSX
    # Asia-Pacific alpha
    "AX",  # ASX Australia
    "NS",  # NSE India
    "BO",  # BSE India
    "SI",  # SGX Singapore
    "KQ",  # KOSDAQ Korea (alpha tickers e.g. CELLTRION)
    # EM alpha
    "SA",  # B3 Brazil (tickers like VALE3, PETR4)
    "JK",  # Jakarta IDX
    "MX",  # BMV Mexico
    "IS",  # Borsa Istanbul
    "SN",  # Santiago Chile
    "JO",  # JSE South Africa
    "QA",  # Qatar Exchange
    "KW",  # Kuwait SE
    "AE",  # UAE (Abu Dhabi + Dubai — remapped from .AD/.DU by _normalize_ticker)
})


# ── ADR / cross-listing map for numeric-suffix tickers ───────────────────────
# Maps local numeric Yahoo ticker → US-listed symbol that FMP tracks for
# analyst consensus (revenue + EPS estimates).
#
# Only include tickers where the US listing has REAL analyst coverage:
#   - NYSE/NASDAQ direct listings (BABA, TSM) → best quality
#   - Liquid NYSE ADRs (TM, SONY, NTDOY) → good quality
#   - OTC ADRs (TCEHY, SFTBY) → present but fewer analysts
# Do NOT add illiquid OTC stubs (HXSCL for SK Hynix, SSNLF for Samsung)
# — FMP will have no or stale data for those.
#
# MAINTENANCE: Add entries when a major APAC company lists a US ADR.
# Remove entries if the US listing is delisted or becomes illiquid.
# Check FMP symbol validity: https://financialmodelingprep.com/financial-statements/{symbol}
ADR_MAP: dict = {
    # ── Taiwan ─────────────────────────────────────────────────────────────
    "2330.TW": "TSM",    # TSMC → NYSE (~$600B, heavily covered by US analysts)
    "2303.TW": "UMC",    # United Micro Electronics → NYSE ADR
    "3711.TW": "ASX",    # ASE Technology → NYSE ADR
    "2454.TW": "MDTKF",  # MediaTek → OTC (limited coverage, skip if FMP misses)
    # ── Japan ──────────────────────────────────────────────────────────────
    "7203.T":  "TM",     # Toyota → NYSE ADR (liquid, good coverage)
    "6758.T":  "SONY",   # Sony → NYSE ADR
    "7974.T":  "NTDOY",  # Nintendo → OTC ADR
    "9432.T":  "NTTYY",  # NTT → OTC ADR
    "9984.T":  "SFTBY",  # SoftBank Group → OTC ADR
    "9433.T":  "KDDIY",  # KDDI → OTC ADR
    "4519.T":  "CHGCY",  # Chugai Pharma → OTC ADR
    "6954.T":  "FANUY",  # Fanuc → OTC ADR
    "8001.T":  "ITOCY",  # Itochu → OTC ADR
    "6367.T":  "DAIIF",  # Daikin → OTC (limited, try)
    "4063.T":  "SHECY",  # Shin-Etsu Chemical → OTC ADR
    "6501.T":  "HTHIY",  # Hitachi → OTC ADR
    "8035.T":  "TOELY",  # Tokyo Electron → OTC ADR
    "6857.T":  "AVANF",  # Advantest → OTC
    # ── Hong Kong ──────────────────────────────────────────────────────────
    "0700.HK": "TCEHY",  # Tencent → OTC ADR
    "9988.HK": "BABA",   # Alibaba → NYSE listed directly
    "9618.HK": "JD",     # JD.com → NASDAQ listed directly
    "9999.HK": "NTES",   # NetEase → NASDAQ listed directly
    "3690.HK": "MPNGF",  # Meituan → OTC (limited)
    "2382.HK": "SMPRY",  # Sunny Optical → OTC (try)
    # ── Korea ──────────────────────────────────────────────────────────────
    # Samsung (005930.KS) and SK Hynix (000660.KS) have only illiquid OTC stubs
    # — intentionally excluded. No quality US analyst consensus exists.
    # ── China A-shares ─────────────────────────────────────────────────────
    # A-shares (.SS/.SZ) generally have no US ADR; omitted.
    # Exceptions handled via HK dual-listings if applicable.
}


def get_fmp_symbol(ticker: str) -> str:
    """Return the best FMP symbol to use for analyst estimates.

    Logic:
      1. If ticker is in ADR_MAP, return the US ADR symbol — FMP has
         full US analyst consensus (rev estimate, EPS estimate) for it.
      2. Otherwise strip the exchange suffix for the /stable/earnings
         endpoint (which is US-centric and only matches bare symbols).

    Note: for fetch_fmp_single() which uses /income-statement/{symbol},
    the suffixed form (_yahoo_to_fmp) is more correct for non-US tickers.
    Use this function only for the /stable/earnings consensus path.
    """
    if ticker in ADR_MAP:
        return ADR_MAP[ticker]
    return ticker.split(".")[0].upper()



def _normalize_ticker(t: str) -> str:
    """Normalize a raw MSCI CSV ticker to the correct Yahoo Finance format.

    Handles all known systematic differences between MSCI/Bloomberg notation
    and Yahoo Finance URL format:

    0. TICKER_OVERRIDES exact match: BRKB -> BRK-B, HEIA -> HEI-A
    1. London double-dot:    BA..L      -> BA.L
    2. Turkey E-class:       ASELS.E.IS -> ASELS.IS  (also dash form -E.IS)
    3. Thailand NVDR R-class:ADVANC.R.BK -> ADVANC.BK
    4. UAE suffix remap:     AIRARABIA.AD -> AIRARABIA.AE / EMAAR.DU -> EMAAR.AE
    5. Canada/Chile/other multi-dot class shares:
                             RCI.B.TO -> RCI-B.TO, GIB.A.TO -> GIB-A.TO,
                             BAJAJ.AUTO.NS -> BAJAJ-AUTO.NS
       Rule: SYMBOL.PART.EXCHANGE (exactly 2 dots) -> SYMBOL-PART.EXCHANGE
    6. Mexico voting-class asterisk: AC*.MX -> AC.MX
       iShares XLS marks dual-class Mexican shares with *; yfinance rejects it.
    """
    t = t.strip()
    if not t:
        return t

    # 0. TICKER_OVERRIDES exact match (bare-symbol variants: BRKB, HEIA, etc.)
    if t in TICKER_OVERRIDES:
        return TICKER_OVERRIDES[t]

    # 1. London double-dot: BA..L -> BA.L
    t = re.sub(r'\.\.[A-Z]', lambda m: '.' + m.group(0)[-1], t)
    t = re.sub(r'\.\.([A-Z]+)$', r'.\1', t)

    # 2. Turkey: strip E-class marker  (ASELS.E.IS or ASELS-E.IS -> ASELS.IS)
    t = re.sub(r'\.E\.IS$', '.IS', t)
    t = re.sub(r'-E\.IS$',   '.IS', t)

    # 3. Thailand NVDR: strip R-class marker  (ADVANC.R.BK -> ADVANC.BK)
    t = re.sub(r'\.R\.BK$', '.BK', t)

    # 4. UAE suffix remap  (.AD -> .AE, .DU -> .AE)
    t = re.sub(r'\.(AD|DU)$', '.AE', t)

    # 5. General 2-dot rule: SYMBOL.PART.EXCHANGE -> SYMBOL-PART.EXCHANGE
    t = re.sub(r'^([A-Z][A-Z0-9]*)\.([A-Z][A-Z0-9]*)\.([A-Z]+)$', r'\1-\2.\3', t)

    # 6. Mexico asterisk: AC*.MX -> AC.MX
    t = re.sub(r'\*\.', '.', t)

    return t


# ── Universe loader ───────────────────────────────────────────────────────────

def load_universe() -> pd.DataFrame:
    """Load MSCI World + MSCI EM CSVs and return a deduplicated ticker universe.

    Sources loaded (in priority order — lower number wins for duplicates):
      1. MSCI World (~1,300 developed-market stocks)
      2. MSCI EM standard (~830 emerging-market stocks)

    Both CSVs are generated by tools/update_msci_world_classification.py v3+,
    which reads the iShares XLS files directly and resolves exchange suffixes
    from the exact exchange-name column (no regex, no country ETFs).

    Each CSV is skipped gracefully if the file doesn't exist (first-run safe).
    Returns DataFrame with columns: Ticker, Company, Country, Sector.
    """
    _sources = [
        ("world", MSCI_CSV),
        ("em",    MSCI_EM_CSV),
    ]

    frames = []
    for source_key, csv_path in _sources:
        if not csv_path.exists():
            print(f"[universe] {source_key.upper()} CSV not found at {csv_path} — skipped "
                  f"(run update_msci_world_classification.py --universe {source_key} to generate)")
            continue
        try:
            df = pd.read_csv(csv_path, dtype=str)
            df["Ticker"] = df["Ticker"].astype(str).str.strip()
            df = df[df["Ticker"].str.len() > 0]
            df["_source"] = source_key
            df["_priority"] = _SOURCE_PRIORITY.get(source_key, 99)
            frames.append(df)
            print(f"[universe] Loaded {len(df):>5} tickers from {source_key.upper()} CSV")
        except Exception as e:
            print(f"[universe] Error loading {source_key.upper()} CSV: {e}")

    if not frames:
        return pd.DataFrame(columns=["Ticker", "Company", "Country", "Sector"])

    combined = pd.concat(frames, ignore_index=True)

    # Dedup: sort ascending so lowest priority number (= highest priority) wins
    combined = combined.sort_values("_priority", ascending=True)
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")
    combined = combined.drop(columns=["_source", "_priority"], errors="ignore")

    # ── Ticker normalization (v1.5.0) ─────────────────────────────────────────
    # Apply BEFORE ghost filter so multi-dot class-share tickers (e.g. RCI.B.TO)
    # are converted to Yahoo format (RCI-B.TO) before the multi-dot ghost check.
    before_norm = combined["Ticker"].copy()
    combined["Ticker"] = combined["Ticker"].apply(_normalize_ticker)
    normalized = (combined["Ticker"] != before_norm).sum()
    if normalized:
        print(f"[universe] Normalized {normalized} tickers via _normalize_ticker "
              f"(Turkey -E, Thailand .R, UAE .AD/.DU→.AE, class-share dots→dashes, double-dots)")
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")

    # Apply runtime ticker overrides (symbol renames, corporate actions)
    combined["Ticker"] = combined["Ticker"].replace(TICKER_OVERRIDES)
    combined = combined.drop_duplicates(subset=["Ticker"], keep="first")

    # Ghost filter — safety net for anything that slipped through CSV build
    before = len(combined)
    combined = combined[~combined["Ticker"].apply(is_ghost_ticker)]
    dropped = before - len(combined)
    if dropped:
        print(f"[universe] Dropped {dropped} ghost/placeholder tickers")

    # Dead-market suffix filter — remove exchanges where yfinance returns 0 usable data.
    # These are defined in DEAD_MARKET_SUFFIXES (KL, PS, AD, DU).
    # Filtering here means gc_engine and scan.py never see these tickers at all —
    # they cannot drift into the "active" count via stale cache entries.
    before = len(combined)
    combined = combined[~combined["Ticker"].apply(
        lambda t: (t.rsplit(".", 1)[-1] if "." in t else "US") in DEAD_MARKET_SUFFIXES
    )]
    dead_sfx_dropped = before - len(combined)
    if dead_sfx_dropped:
        print(f"[universe] Dropped {dead_sfx_dropped} tickers on dead-market exchanges "
              f"({', '.join(sorted(DEAD_MARKET_SUFFIXES))})")

    # Known-dead ticker filter — permanently invalid symbols (sanctioned, no Yahoo support).
    # Defined in KNOWN_DEAD_TICKERS. Filtering here avoids wasting gc_engine API calls.
    before = len(combined)
    combined = combined[~combined["Ticker"].isin(KNOWN_DEAD_TICKERS)]
    known_dead_dropped = before - len(combined)
    if known_dead_dropped:
        print(f"[universe] Dropped {known_dead_dropped} known-dead tickers "
              f"(sanctioned / no Yahoo Finance support)")

    print(f"[universe] Total: {len(combined)} unique tickers "
          f"(after ghost={dropped}, dead_suffix={dead_sfx_dropped}, known_dead={known_dead_dropped})")
    return combined.reset_index(drop=True)
